// shared/permissions.js
// Centralized permission matrix

import { ROLES, IPC_CHANNELS } from './constants.js';

export const PERMISSIONS = {
  // Orders
  TAKE_ORDERS: 'orders:take',
  VIEW_RECENT_ORDERS: 'orders:view_recent',
  VOID_ORDERS: 'orders:void',

  // Shifts
  MANAGE_SHIFTS: 'shifts:manage',

  // Cash
  RECORD_CASH_MOVEMENT: 'cash:record_movement',
  VIEW_CASH_MOVEMENTS: 'cash:view_movements',

  // Inventory
  VIEW_INVENTORY: 'inventory:view',
  EDIT_INVENTORY: 'inventory:edit',
  CONFIRM_INVENTORY: 'inventory:confirm',
  MANAGE_INVENTORY_ITEMS: 'inventory:manage_items',

  // Reports
  VIEW_DAILY_REPORTS: 'reports:view_daily',
  VIEW_DETAILED_REPORTS: 'reports:view_detailed',
  EXPORT_REPORTS: 'reports:export',

  // Menu & Recipes
  VIEW_MENU: 'menu:view',
  MANAGE_MENU: 'menu:manage',
  MANAGE_RECIPES: 'menu:recipes',

  // Admin
  MANAGE_STAFF: 'admin:manage_staff',
  MANAGE_SETTINGS: 'admin:manage_settings',
  MANAGE_BACKUPS: 'admin:manage_backups',
  MANAGE_SYNC: 'admin:manage_sync',
  VIEW_SYSTEM_HEALTH: 'admin:view_health',
};

// Map each role to their set of permitted actions
export const ROLE_PERMISSIONS = {
  [ROLES.STAFF]: [
    PERMISSIONS.TAKE_ORDERS,
    PERMISSIONS.VIEW_RECENT_ORDERS,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.RECORD_CASH_MOVEMENT,
    PERMISSIONS.VIEW_MENU,
  ],
  [ROLES.ADMIN_STAFF]: [
    PERMISSIONS.TAKE_ORDERS,
    PERMISSIONS.VIEW_RECENT_ORDERS,
    PERMISSIONS.VOID_ORDERS,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.RECORD_CASH_MOVEMENT,
    PERMISSIONS.VIEW_CASH_MOVEMENTS,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.EDIT_INVENTORY,
    PERMISSIONS.CONFIRM_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY_ITEMS,
    PERMISSIONS.VIEW_DAILY_REPORTS,
    PERMISSIONS.VIEW_DETAILED_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // Admin has all permissions
  [ROLES.REMOTE_ADMIN]: [
    PERMISSIONS.MANAGE_SYNC,
    PERMISSIONS.VIEW_DAILY_REPORTS,
    PERMISSIONS.VIEW_DETAILED_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_SYSTEM_HEALTH,
  ],
};

// Map IPC channels to required permissions for automatic validation
export const CHANNEL_PERMISSIONS = {
  // Shifts
  [IPC_CHANNELS.SHIFTS_OPEN]: PERMISSIONS.MANAGE_SHIFTS,
  [IPC_CHANNELS.SHIFTS_CLOSE]: PERMISSIONS.MANAGE_SHIFTS,
  [IPC_CHANNELS.SHIFTS_CURRENT]: PERMISSIONS.MANAGE_SHIFTS,
  [IPC_CHANNELS.SHIFTS_FORCE_CLOSE]: PERMISSIONS.MANAGE_SHIFTS,

  // Orders
  [IPC_CHANNELS.ORDERS_CREATE]: PERMISSIONS.TAKE_ORDERS,
  [IPC_CHANNELS.ORDERS_VOID]: PERMISSIONS.VOID_ORDERS,
  [IPC_CHANNELS.ORDERS_LIST]: PERMISSIONS.VIEW_RECENT_ORDERS,
  [IPC_CHANNELS.ORDERS_GET]: PERMISSIONS.VIEW_RECENT_ORDERS,
  [IPC_CHANNELS.ORDERS_RECENT]: PERMISSIONS.VIEW_RECENT_ORDERS,

  // Menu Read
  [IPC_CHANNELS.MENU_CATEGORIES]: PERMISSIONS.VIEW_MENU,
  [IPC_CHANNELS.MENU_PRODUCTS]: PERMISSIONS.VIEW_MENU,
  [IPC_CHANNELS.MENU_VARIANTS]: PERMISSIONS.VIEW_MENU,
  [IPC_CHANNELS.MENU_MODIFIERS]: PERMISSIONS.VIEW_MENU,
  [IPC_CHANNELS.MENU_CATALOG]: PERMISSIONS.VIEW_MENU,

  // Menu Admin
  [IPC_CHANNELS.MENU_ADMIN_CREATE_CATEGORY]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_UPDATE_CATEGORY]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_CREATE_PRODUCT]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_UPDATE_PRODUCT]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_CREATE_VARIANT]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_UPDATE_VARIANT]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_DELETE_VARIANT]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_CREATE_MODIFIER]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_UPDATE_MODIFIER]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_MANAGE_MODIFIERS]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_REORDER]: PERMISSIONS.MANAGE_MENU,
  [IPC_CHANNELS.MENU_ADMIN_TOGGLE_ACTIVE]: PERMISSIONS.MANAGE_MENU,

  // Recipes
  [IPC_CHANNELS.RECIPES_GET]: PERMISSIONS.VIEW_MENU,
  [IPC_CHANNELS.RECIPES_UPDATE]: PERMISSIONS.MANAGE_RECIPES,
  [IPC_CHANNELS.RECIPES_COVERAGE]: PERMISSIONS.VIEW_MENU,

  // Inventory
  [IPC_CHANNELS.INVENTORY_ITEMS]: PERMISSIONS.VIEW_INVENTORY,
  [IPC_CHANNELS.INVENTORY_LOG]: PERMISSIONS.VIEW_INVENTORY,
  [IPC_CHANNELS.INVENTORY_UPDATE_LOG]: PERMISSIONS.EDIT_INVENTORY,
  [IPC_CHANNELS.INVENTORY_CONFIRM]: PERMISSIONS.CONFIRM_INVENTORY,
  [IPC_CHANNELS.INVENTORY_SAVE_ITEM]: PERMISSIONS.MANAGE_INVENTORY_ITEMS,

  // Reports
  [IPC_CHANNELS.REPORTS_DAILY_SALES]: PERMISSIONS.VIEW_DAILY_REPORTS,
  [IPC_CHANNELS.REPORTS_SHIFT_SUMMARY]: PERMISSIONS.VIEW_DAILY_REPORTS,
  [IPC_CHANNELS.REPORTS_PRODUCT_MIX]: PERMISSIONS.VIEW_DETAILED_REPORTS,
  [IPC_CHANNELS.REPORTS_INVENTORY]: PERMISSIONS.VIEW_DETAILED_REPORTS,
  [IPC_CHANNELS.REPORTS_WASTE]: PERMISSIONS.VIEW_DETAILED_REPORTS,
  [IPC_CHANNELS.REPORTS_EXPORT_CSV]: PERMISSIONS.EXPORT_REPORTS,

  // Staff Management
  [IPC_CHANNELS.STAFF_LIST]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_CREATE]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_UPDATE]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_DEACTIVATE]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_REACTIVATE]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_RESET_PASSWORD]: PERMISSIONS.MANAGE_STAFF,
  [IPC_CHANNELS.STAFF_RESET_PIN]: PERMISSIONS.MANAGE_STAFF,

  // Settings
  [IPC_CHANNELS.SETTINGS_GET_ALL]: PERMISSIONS.MANAGE_SETTINGS,
  [IPC_CHANNELS.SETTINGS_UPDATE]: PERMISSIONS.MANAGE_SETTINGS,

  // Dashboard Overview
  [IPC_CHANNELS.DASHBOARD_OVERVIEW]: PERMISSIONS.VIEW_DAILY_REPORTS,
  [IPC_CHANNELS.DASHBOARD_TREND]: PERMISSIONS.VIEW_DAILY_REPORTS,

  // Cash Management
  [IPC_CHANNELS.CASH_RECORD_MOVEMENT]: PERMISSIONS.RECORD_CASH_MOVEMENT,
  [IPC_CHANNELS.CASH_LIST_MOVEMENTS]: PERMISSIONS.VIEW_CASH_MOVEMENTS,

  // System
  [IPC_CHANNELS.BACKUP_RUN_NOW]: PERMISSIONS.MANAGE_BACKUPS,
  [IPC_CHANNELS.BACKUP_LIST]: PERMISSIONS.MANAGE_BACKUPS,
  [IPC_CHANNELS.BACKUP_STATUS]: PERMISSIONS.MANAGE_BACKUPS,
  [IPC_CHANNELS.SYNC_STATUS]: PERMISSIONS.MANAGE_SYNC,
  [IPC_CHANNELS.SYNC_TRIGGER]: PERMISSIONS.MANAGE_SYNC,
  [IPC_CHANNELS.SYNC_LOG]: PERMISSIONS.MANAGE_SYNC,
  [IPC_CHANNELS.HEALTH_CHECK]: PERMISSIONS.VIEW_SYSTEM_HEALTH,
  [IPC_CHANNELS.HEALTH_DB_INTEGRITY]: PERMISSIONS.VIEW_SYSTEM_HEALTH,
  [IPC_CHANNELS.HEALTH_STATUS]: PERMISSIONS.VIEW_SYSTEM_HEALTH,
};

export function hasPermission(role, permission) {
  const allowed = ROLE_PERMISSIONS[role] || [];
  return allowed.includes(permission);
}
